# Generated by Django 4.1.4 on 2022-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('weekend', models.CharField(max_length=10)),
                ('gross', models.CharField(max_length=10)),
                ('weeks', models.CharField(max_length=3)),
                ('category', models.CharField(choices=[('b', 'box Office'), ('t', 'Top250'), ('p', 'Popular')], max_length=1, verbose_name='Category')),
            ],
        ),
    ]
