# Generated by Django 4.1.4 on 2022-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weeks', models.CharField(max_length=3)),
            ],
        ),
    ]
