# Generated by Django 4.1.4 on 2022-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tite',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
