# Generated by Django 4.1.4 on 2022-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gross',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='weekend',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
